### PR TITLE
Added the Hebrew translation

### PR DESCRIPTION
**Pull request by yarons**
We need to rethink about a proper RTL interface because translation is only part of the localization process.

### CODE REVIEW

**Comment by bkmgit** [comment]
Do you have suggestions for this or a pointer to a good example model which we could follow?

**Comment by yarons** [comment]
There are several guides online but what I usually do is create a branch with css that has direction set to rtl and then just flip everything that looks weird, after we'll have such test environment I'll submit the push requests. 

These changes also apply to Arabic and Persian.

**Comment by kellerben** [comment]
can you please check if everything is as expected?
https://dudle.inf.tu-dresden.de/?lang=he

**Comment by yarons** [comment]
Nope, try adding `dir=rtl` to the body or html tag, if you can only do it using CSS then try adding: body{direction:rtl}

**Comment by yarons** [comment]
This is what I achieved playing around with the CSS after adding `dir="rtl"` after `xml:lang="en"` (I changed that to `he` accordingly):
screen shot 2017-07-05 at 11 03 38

Where can I commit specific changed to RTL?
Can you include a special RTL CSS in `he` and I will just add all the additions to it?

**Comment by yarons** [comment]
Any news? Anything you want me to do or check?

**Comment by bkmgit** [comment]
Hi, can you add an example CSS file for Hebrew along with instructions?

**Comment by kellerben** [comment]
I added a patch. Can you please look at https://dudle.inf.tu-dresden.de/?lang=he if everything is like you expect?

**Pull request merged**
